apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ondemand-t3-small
spec:
  weight: 100
  limits:
    cpu: 2
    memory: 4Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app-infra
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
