# 1. THE SPOT POOL (90% Priority)
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-t2-micro
spec:
  weight: 10  # Higher weight means Karpenter prefers this pool
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app-infra
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small"] # ONLY t2.micro
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
# 2. THE ON-DEMAND POOL (10% Fallback)
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ondemand-t2-micro
spec:
  weight: 90 # Lower weight
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app-infra
      requirements:
        - key: "role"
          operator: In
          values: ["app"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small"] # ONLY t2.micro
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
